spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  sleuth:
    trace-id128: true
  zipkin:
    enabled: false
  cache:
    cache-names: hello
  main:
      allow-bean-definition-overriding: true
  profiles:
    include: oauth, real-db # https://console.cloud.google.com/apis/credentials/oauthclient
logging:
  level:
    com.inspire12.practice.api: info
    root: info


management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "httptrace"
server:
  port: 8080

api-url: dummyjson.com