spring:
  datasource:
    primary:
      url: jdbc:mysql://${MYSQL_URL:localhost:3306}/inspire12_api?serverZoneId=Asia/Seoul;
      username: root
      password: password
      initialization-mode: always


    slave:
      url: jdbc:mysql://${MYSQL_URL:localhost:3306}/inspire12_api?serverZoneId=Asia/Seoul;
      username: root
      password: password

    community:
      url: jdbc:mysql://${MYSQL_URL:localhost:3306}/inspire12_community?serverZoneId=Asia/Seoul;
      username: root
      password: password
      initialization-mode: always

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  batch:
    job:
      enabled: false

  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: create
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  sql:
    init:
      mode: always

logging:
  level:
    root: info

kafka:
  enabled: false

api-url: dummyjson.com
