spring:
    session:
    store-type: jdbc
    jdbc.initialize-schema: always
    main:
        allow-bean-definition-overriding: true

sleuth:
    trace-id128: true

zipkin:
    enabled: false

cache:
    cache-names: hello

management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "httptrace"