spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

  datasource:
    primary:
      url: jdbc:h2:~/inspire12_api;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      username: sa
      initialization-mode: always

    slave:
      #    jdbc-url: jdbc:h2:mem:inspire12_api;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      url: jdbc:h2:~/inspire12_api;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      username: sa

    community:
      url: jdbc:h2:~/inspire12_community;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
      username: sa
      initialization-mode: always

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  batch:
    job:
      enabled: false

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
  sql:
    init:
      mode: always

logging:
  level:
    root: info

kafka:
  enabled: false

api-url: dummyjson.com
