spring:
  profiles:
    include: oauth,real-db
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            security: SecurityConfig