primary:
    datasource:
        jdbc-url: jdbc:h2:mem:inspire12_api;MODE=MYSQL
        username: sa
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
        jdbc.initialize-schema: always
community:
    datasource:
        jdbc-url: jdbc:h2:mem:inspire12_community;MODE=MYSQL
        username: sa
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
        jdbc.initialize-schema: always

spring:
    session:
        store-type: jdbc
        jdbc.initialize-schema: always

    batch:
        job:
            enabled: false

    h2:
        console:
            enabled: true
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
            username: sa
    jpa:
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                storage_engine: innodb
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
    level:
        root: info