datasource:
  primary:
    jdbc-url: jdbc:h2:mem:inspire12_api;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    jdbc.initialize-schema: always
  slave:
    jdbc-url: jdbc:h2:mem:inspire12_api;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa

  community:
    jdbc-url: jdbc:h2:mem:inspire12_community;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa

spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  batch:
    job:
      enabled: false

  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    root: info